---
platform: linux

image_resource:
 type: docker-image
 source:
   repository: pivotalservices/openstack-tools

inputs:
- name: pcf-pipelines

params:
  EXTERNAL_NETWORK:
  INFRA_NETWORK:
  INFRA_SUBNET:
  ERT_NETWORK:
  ERT_SUBNET:
  SERVICES_NETWORK:
  SERVICES_SUBNET:
  SERVICESOD_NETWORK:
  SERVICESOD_SUBNET:
  ADMIN_ROUTER:
  BACKEND_ROUTER:
  SECGROUP_NAME:

  OS_PROJECT_ID:
  OS_REGION_NAME:
  OS_USER_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_IDENTITY_API_VERSION:
  OS_PASSWORD:
  OS_AUTH_URL:
  OS_USERNAME:
  PRE_OS_CACERT:
  OS_INTERFACE:

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/pave-openstack/task.sh
