# These should probably be static except for the 'external-net'
# external_network refers to the network where I request floating IP's.
external_network: external-net
infra_network: infra
infra_subnet: 10.1.0.0/24
ert_network: ert
ert_subnet: 10.2.0.0/24
services_network: services
services_subnet: 10.3.0.0/24
servicesod_network: services_od
servicesod_subnet: 10.4.0.0/24
admin_router: admin_router
backend_router: backend_router
secgroup_name: cf

# These are simply the project users credentials, downloaded from Horizon.
# The pre_os_cacert is the root CA cert, only needed if the openstack API's
# are fronted by a self-signed SSL certificate.
os_project_id:
os_region_name:
os_user_domain_name:
os_project_name:
os_identity_api_version:
os_password:
os_auth_url:
os_username:
os_interface:
pre_os_cacert:

## Pivnet Requirements
pivnet_api_token:

## What to name the image in glance
ops_mgr_img_name:
ops_mgr_sec_grp:
ops_mgr_key_name:
ops_mgr_flv_name:
ops_mgr_srv_name:
