---

platform: linux

image_resource:
 type: docker-image
 source:
   repository: pivotalservices/openstack-tools

params:
  EXTERNAL_NETWORK:
  INFRA_NETWORK:
  PRE_OS_CACERT:
  OS_PROJECT_ID:
  OS_REGION_NAME:
  OS_USER_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_IDENTITY_API_VERSION:
  OS_PASSWORD:
  OS_AUTH_URL:
  OS_USERNAME:
  PRE_OS_CACERT:
  OS_INTERFACE:
  OPS_MGR_IMG_NAME:
  OPS_MGR_SEC_GRP:
  OPS_MGR_KEY_NAME:
  OPS_MGR_FLV_NAME:
  OPS_MGR_SRV_NAME:

inputs:
  - name: pcf-pipelines
  - name: pivnet-opsman-product

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/boot-opsman.sh
